version: "3.8"

services:
  postgres:
    image: postgres:14.4
    restart: always
    container_name: finejob-db
    environment:
      POSTGRES_DB: finejob
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
